### ISSUE TITLE
swagger v0.28.0 generates array flags that does not compile

### ISSUE THREAD

**Issue by youyuanwu** [go-swagger/dockerctl#12]
```
      parameters:
        - name: "names"
          in: "query"
          description: "Image names to filter by"
          type: "array"
          items:
            type: "string"
```
Spec with query parameter generates code:
```go
		namesFlagValues, err := cmd.Flags().GetStringSlice(namesFlagName)
		if err != nil {
			return err, false
		}
		m.Names = &namesFlagValues
~~~~~~~~^ is array but not array pointer
```
template that produces this line is 
```
        m.{{ pascalize .Name }} = {{- if .IsNullable }}&{{- end }}{{ $flagValueVar }}
```
Seems like the array is marked as nullable, but should not have been.

bug is introduced by : https://github.com/go-swagger/go-swagger/pull/2620
